name: MauiMicroMvvm PR Validation

on:
  pull_request:
    branches: [ master ]
    paths:
      - "sample/**"
      - "src/**"
      - "test/**"
      - "version.json"
      - "build.slnf"
      - ".github/workflows/pr.yml"

jobs:
  build:
    uses: avantipoint/workflow-templates/.github/workflows/dotnet-build.yml@master
    with:
      name: MauiMicroMvvm
      solution-path: build.slnf
      install-workload: maui

  validate:
    needs: [build]
    runs-on: macos-latest
    steps:
      - name: Setup Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '15.2'
      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x
      - name: Download Artifacts
        uses: actions/download-artifact@v4
        with:
          name: NuGet
          path: Artifacts
      - name: Install Templates
        run: dotnet new install Artifacts/AvantiPoint.MauiMicroMvvm.Templates.*.nupkg
      - name: Add Local Source
        run: dotnet nuget add source ${{ github.workspace }}/Artifacts --name Artifacts
      - name: Create Test Project
        run: dotnet new maui-micro -o TestProject
      - name: Workload Install
        run: dotnet workload install maui
        working-directory: TestProject
      - name: Build Project
        run: dotnet build
        working-directory: TestProject